language: node_js
node_js:
  - '8'
  - '10'
branches:
  only:
    - master
script:
  - git config --global user.name "Jonny Burger"
  - git config --global user.email "hi@jonny.io"
  - echo "machine github.com login JonnyBurger password ${GH_TOKEN}" > ~/.netrc
  - cd website && npm install && GIT_USER=JonnyBurger npm run publish-gh-pages
